# OpenCV git link
cvGitUrl: "https://github.com/opencv/opencv.git"

# Define OpenCV version to install
cvVersion: "3.4"

# OpenCV Home Folder
cvHomeDir: "/opt/opencv"

# Directory for installation
cvInstallDir: "{{cvHomeDir}}/installation"

# Dependencies List
cvDependencies:
  - devscripts
  - build-essential
  - checkinstall
  - cmake
  - pkg-config
  - yasm
  - git 
  - gfortran
  - libjpeg8-dev 
  - libjasper-dev 
  - libpng12-dev
  - libtiff5-dev
  - libtiff-dev
  - libavcodec-dev 
  - libavformat-dev 
  - libswscale-dev 
  - libdc1394-22-dev
  - libxine2-dev 
  - libv4l-dev
  - libgstreamer0.10-dev 
  - libgstreamer-plugins-base0.10-dev
  - libgtk2.0-dev
  - libtbb-dev
  - qt5-default
  - libatlas-base-dev
  - libfaac-dev
  - libmp3lame-dev
  - libtheora-dev
  - libvorbis-dev
  - libxvidcore-dev
  - libopencore-amrnb-dev
  - libopencore-amrwb-dev
  - libavresample-dev
  - x264
  - v4l-utils

# Optional Dependencies List
cvOptionalDependencies:
  - libprotobuf-dev
  - protobuf-compiler
  - libgoogle-glog-dev
  - libgflags-dev
  - libgphoto2-dev
  - libeigen3-dev
  - libhdf5-dev
  - doxygen
