---
- name: Install add-apt-repostory
  apt:
    name  : software-properties-common
    state : latest
  become  : yes

- name: Add Oracle Java Repository
  apt_repository:
    repo: 'ppa:webupd8team/java'
  become: yes

- name: Accept Java 8 License
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'
  become: true

- name: Install Oracle Java 8
  apt:
    name: '{{ item  }}'
    state: latest
    update_cache: yes
  loop:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  become: yes
